describe("employee")
it("should prompt the user for the manager's information first")
it("should prompt user for info about the engineer when engineer selected")
it("should prompt user for info about the intern when intern selected")
it("should end the application when finished building team profile selected")
it("should generate an html file that displays a nicely formatted team roster based on user input")