decscribe("intern")
it("should prompt the user for intern's full name")
it("should prompt the user for intern's job title")
it("should prompt the user for intern's ID mumber")
it("should prompt user for intern's email")
it("should prompt the user for the intern's school name")
it("should prompt the user to select engineer or intern or to finish building the team profile")