describe("manager")
it("should prompt the user for manager's full name")
it("should prompt the user for manager's ID mumber")
it("should prompt user for manager's email")
it("should prompt the user for the team's office number")
it("should return to main menu after completing this profile")
it("should prompt the user to select engineer or intern or to finish building the team profile")